### ISSUE TITLE
Exporting does not actually save the file and does not generate an error message.

### ISSUE THREAD

**Issue by KarlBaumann** [irplus-remote/irplus-codes.github.io#258] opened 2016-07-25 19:37 UTC
I have managed to export files few times, but I don't what exactly triggers this error.

**Comment by irplus-remote** [comment] 2016-07-25 19:38
Export to the filesystem? Did you remove any permissions or denied them?

**Comment by KarlBaumann** [comment] 2016-07-25 19:43
Yes, exporting to email does not work at all, because I dont have email set up.

No, I didnt know you can change file permissions on Android :) It did work now after I restarted the phone.

**Comment by KarlBaumann** [comment] 2016-07-25 19:47
I think it would be good to implement some kind of confirmation message if files were saved successfully or error message if saving failed.

**Comment by irplus-remote** [comment] 2016-07-25 19:50
Usually on the bottom there should be a confirmation or error popup, didnt it come for you? 

Android version?

![image](https://cloud.githubusercontent.com/assets/14196521/17115009/c111fee2-52b1-11e6-9dbf-a8037bb6ba78.png)

**Comment by KarlBaumann** [comment] 2016-07-25 19:53
Hmm, yes, there was this icon, but it is always the same, no matter if write fails or not.
I have latest Cyanogenmod

**Comment by irplus-remote** [comment] 2016-07-25 19:54
Strange, did you try to write on internal storage or on external sd? what path was it exactly? (or just the "auto" setting?)

**Comment by KarlBaumann** [comment] 2016-07-25 19:58
On external with manual path it has never worked, I have managed to write to custom path in internal card and also writing in "auto" worked after reboot. It looks like it might have something to do with switching to "USB file transfer" mode

**Comment by irplus-remote** [comment] 2016-07-25 20:05
please post the exact cyanogenmod revision, which phone. If i manage to get one ill check it out further. Until then i guess i can't reproduce it

The code to save is this. Its virtually impossible that it passes. So if there's an error it's probably in the OS/filesystem layer, since for every error while saving it would throw an exception
```
 File file = new File(....);
                try {
                   FileOutputStream fos = new FileOutputStream(file);
		fos.write(str.getBytes());
		fos.close();
                }catch(Exception e){
                    errorsWhileSaving = true;
                }
```

In case you or some one else has a suggestion to offer for the code above feel free.

**Comment by KarlBaumann** [comment] 2016-07-25 20:20
I don't know java.
![screenshot_20160725-221905](https://cloud.githubusercontent.com/assets/11026930/17115996/08beaf20-52b6-11e6-999e-aa78e5de09e2.png)

**Comment by irplus-remote** [comment] 2016-08-23 11:41
Cannot reproduce on multiple devices, will close this for now. If you have ideas on how to reproduce let me know. (Maybe CM issue)

**Closed by irplus-remote** 2016-08-23 11:41 UTC
Labels: enhancement
