### ISSUE TITLE
HTC One M7 not working (Lineage OS 14.1 / Android 7.1.1)

### ISSUE THREAD

**Issue by bfayers** [irplus-remote/irplus-codes.github.io#304] opened 2017-02-11 18:44 UTC
Hi, on the M7 it doesn't send any IR. Verified via using a camera. Other apps like: LED RGB Remote from mvmacd on the play store. Quite annoying as this seems to be a good app

**Comment by irplus-remote** [comment] 2017-02-11 18:46
Hi, probably the workaround i built in for the CM roms doesnt work anymore because the id has changed. I have to make a difference for Stock and Custom HTC devices

previously it was "cm_" - could you tell me what it is now?

import android.os.Build;
Build.DISPLAY;

**Comment by bfayers** [comment] 2017-02-11 19:02
Build number in settings shows lineage_ :) app looks great (minus the not working)

**Comment by irplus-remote** [comment] 2017-02-11 19:05
Actually i've now tried something else to avoid non-functioning cases when sense is not detected. I'm now using 

```
   Class.forName(className);
``` 
to check if HTC Sense is on the device - if not it will go for the regular IR api (which can Transmit but not Receive)

Could you please try and check if this build works for you? 

https://drive.google.com/file/d/0B3BPAmebhawpeFJpcGhMS1RiNUU/view?usp=sharing

**Comment by bfayers** [comment] 2017-02-11 19:08
Nope, that doesn't fire unfortunately

**Comment by bfayers** [comment] 2017-02-11 19:11
About the non ability to receive, that kinda annoying since the thing I'm trying to use isn't on the list... I can always try lirc codes I guess

**Comment by irplus-remote** [comment] 2017-02-11 19:12
Damn, maybe the com.htc package is installed some where - i've now tried the "old" way and added "lineage_" to "cm_" 

Try again please:

https://drive.google.com/file/d/0B3BPAmebhawpcnRBcXliazhXYnM/view?usp=sharing

Yea - but receiving is only possible with HTC Sense - there almost nothing i can do - unless there is a way to install the Sense SDK on Lineage

**Comment by bfayers** [comment] 2017-02-11 19:21
Fires! Also https://www.xda-developers.com/xda-external-link/install-htc-sense-apps-on-any-phone-or-rom/

**Comment by irplus-remote** [comment] 2017-02-11 19:23
Cool so the last one is working? then ill just leave it that way for now. However id like to know why it didn't work with the last check. Do you have AndroidStudio installed maybe to conduct a test? 

```

true or false?

hasClass("com.htc.circontrol.CIRControl")

 public static boolean hasClass(String className) {
        try  {
            Class.forName(className);
            return true;
        }  catch (ClassNotFoundException e) {
            return false;
        }
    }

```

**Comment by bfayers** [comment] 2017-02-11 19:31
I don't have android studio, I do have adb can I check with/ that

**Comment by irplus-remote** [comment] 2017-02-11 19:33
Never mind then, ill ask at XDA i guess ill find someone there, or will check the lineage image when i have some time

**Comment by bfayers** [comment] 2017-02-11 19:34
This help https://www.htcdev.com/download_ir_api

**Comment by bfayers** [comment] 2017-02-11 19:35
With a 3.5mm IR could you receive or not?

**Comment by bfayers** [comment] 2017-02-11 19:38
if it helps if you can download that IR api it is zip that looks like:  http://i.imgur.com/Un3Vu4R.png

**Comment by irplus-remote** [comment] 2017-02-11 19:43
Yea im using the api already, but the problem is that sense is needed on the device itself to call the proprietary native methods which do the receiving. Unfortunately with 3.5mm receiving is not possible for now (in theory it is - using the MIC-in) but we would need a analog to digital converter and parser (written in software)

Easiest way is to use a raspberry https://irplus-remote.github.io/#codes

If you need codes for specific devices - just open up a new issue with brand+model. I'll check various databases, chances are good if they aren't too exotic

**Comment by bfayers** [comment] 2017-02-11 19:45
ok

**Comment by irplus-remote** [comment] 2017-04-04 06:51
Should be fixed with latest version

**Closed by irplus-remote** 2017-04-04 06:51 UTC
Labels: bug
