### ISSUE TITLE
Support for USB IR blaster devices?

### ISSUE THREAD

**Issue by lmamakos** [irplus-remote/irplus-codes.github.io#452] opened 2019-07-30 19:44 UTC
Hi!   I've got a OnePlus 6T phone, which has neither IR Blaster nor 3.5mm headphone port.  I used to use AnyMote on a Samsung device with the built-in IR Blaster, but have moved on from that.  So I bought one of these cheap USB IR blasters from amazon:  https://www.amazon.com/gp/product/B07F7GPNF3  but the application they recommend using is horrible.

It would really be great if you supported these devices!  I'd pay money for that!  There seem to be a number of sellers of different variations of these devices around, and they are pretty inexpensive.   It's not only me looking for an alternative to the ZazaRemote application that's not even completely translated from Chinese..  I think you'd find a new crop of customers.

**Comment by irplus-remote** [comment] 2019-07-30 20:08
USB is something properietary. Only for Zaza. I cannot support this without an open-source API

**Comment by Sliicy** [comment] 2019-08-04 08:18
I have a Zaza USB C dongle! Any way I can contribute? Should I run Wireshark over USB and monitor the signals? How can we crack this code?

**Comment by lmamakos** [comment] 2019-08-04 14:52
It shows up looking like a USB HID device on my macOS box, so probably not much acrobatics in talking to it, if only you knew what the payloads were supposed to be.

**Comment by irplus-remote** [comment] 2019-08-04 15:03
Hm maybe if it registers als HID you could try to check what commands are being sent to it? But i think its probably encrypted anyway feel free to investigate :) Unfortunatly i dont have a dongle to do tests

**Comment by Sliicy** [comment] 2019-08-12 06:07
Can you PM? I'll happily send you my remote, or give you temporary remote access to my PC! I'd really like to get this device supported! Also, if you use their app, you could get a free remote (minus shipping) if you shared it with 10 friends?

**Comment by irplus-remote** [comment] 2019-08-12 06:13
Can you contact me via the email inside the app? You can then chat with me on Hangout. I could take a look some time, but i doubt it will be much of help, since there is no PC app to capture the codes. 

Whats the _real_ advantage of using USB-C? I can in fact only see disadvantages.. 1.) The port is on the bottom for most phones, so you have to flip it, you have to disengage it each time you want to use the remote feature.. Compared to an "autonomous" bluetooth solution this feels kinda cumbersome. Also the 3.5mm jack solution is easier to use imho. The only case might be when the phone does not have a 3.5mm jack

**Comment by lmamakos** [comment] 2019-08-14 01:38
My phone (OnePlus 6T) only has a USB-C interface for charging and everything else.  There's no headphone jack.  I mostly use the IR blaster capability when I'm _not_ at home (in a hotel to control the TV and cable box, or in a restaurant to turn down the fan on the HVAC blowing air on more).  The little USB-C dongle (and I think there's a conventional micro-USB variation as well) is nice and small and easy to carry around on your keychain.

The Zaza application has an option to rotate the UI 180 degrees so the orientation is flipped around in the "correct" configuration, but I can do without that.

While the situation isn't the best, there are really no alternatives for recent phones that have no IR blaster (or headphone jack).  Unless I find a USB audio dongle and plug the IR emitter into that, but I have no idea if that would work or not, and would look sorta ugly..

**Comment by Nesh108** [comment] 2021-11-02 08:39
I'm reviving this too: there are lots of devices that **only** work with that ZaZa shady app and I'd like something open source. Did these attempts go anywhere?

I am looking to buy a USB-C IR blaster but cannot find anything else, so I wouldn't mind to support the reverse-engineering effort to support these devices.

**Comment by mm12** [comment] 2022-06-05 01:26
Possibly related question: 
- Is it possible to use a USB-C to 3.5mm jack to make a USB-C IR blaster, or will the DAC mess it up? 
- If it is possible, you may want to put it on the website (under `audio`)

**Comment by Psychomonkey1** [comment] 2022-11-17 14:44
> Possibly related question:
> 
> * Is it possible to use a USB-C to 3.5mm jack to make a USB-C IR blaster, or will the DAC mess it up?
> * If it is possible, you may want to put it on the website (under `audio`)

I have the same question, also having a USB-C to jack adapter. It could solve a lot of problems for recent phones that no longer have headphone jacks :-) .

**Comment by lukatavcer** [comment] 2022-11-21 17:26
> > Possibly related question:
> > 
> > * Is it possible to use a USB-C to 3.5mm jack to make a USB-C IR blaster, or will the DAC mess it up?
> > * If it is possible, you may want to put it on the website (under `audio`)
> 
> I have the same question, also having a USB-C to jack adapter. It could solve a lot of problems for recent phones that no longer have headphone jacks :-) .

did you have any success with this? I would also like to do that

**Comment by mm12** [comment] 2022-12-16 02:03
> > > Possibly related question:
> > > 
> > > * Is it possible to use a USB-C to 3.5mm jack to make a USB-C IR blaster, or will the DAC mess it up?
> > > * If it is possible, you may want to put it on the website (under `audio`)
> > 
> > 
> > I have the same question, also having a USB-C to jack adapter. It could solve a lot of problems for recent phones that no longer have headphone jacks :-) .
> 
> did you have any success with this? I would also like to do that

I didn't even try yet

**Comment by Psychomonkey1** [comment] 2022-12-22 10:53
Hi guys, for me it worked with:
- the irplus WAVE app for Android
- a USB-C <> 3.5mm jack adapter
- a mini infrared blaster 3.5mm jack:
![image](https://user-images.githubusercontent.com/84287856/209118533-b83e4041-8a3f-44df-8354-9866fdc2883c.png)


I was able to load a remote control profile created by an Aussie for my PVM-2950qm. The irplus app profiles are compatible with the irplus wave app.

**Comment by flameshikari** [comment] 2023-02-14 10:28
> Hi guys, for me it worked with:
> 
>     * the irplus WAVE app for Android
> 
>     * a USB-C <> 3.5mm jack adapter
> 
>     * a mini infrared blaster 3.5mm jack:
>       ![image](https://user-images.githubusercontent.com/84287856/209118533-b83e4041-8a3f-44df-8354-9866fdc2883c.png)
> 
> 
> I was able to load a remote control profile created by an Aussie for my PVM-2950qm. The irplus app profiles are compatible with the irplus wave app.

Can you share your phone model and adapter name please?

**Comment by swinokur** [comment] 2023-02-18 05:00
Hi All,
After building a couple of ir blasters out of LEDs and 3.5mm jacks for my LG G7 - which worked, but do not have very good range...

In a spirit of experimentation I purchased a couple of these USB-C devices from amazon:
https://www.amazon.com/dp/B083SNBP5W
and
https://www.amazon.com/dp/B07DFZ56MD

Here's some information that I dug up that I hope will be useful!

Plugging these into windows they both enumerate as the same device:

```
    ---------------------- Device Descriptor ----------------------
bLength                  : 0x12 (18 bytes)
bDescriptorType          : 0x01 (Device Descriptor)
bcdUSB                   : 0x110 (USB Version 1.10)
bDeviceClass             : 0x00 (defined by the interface descriptors)
bDeviceSubClass          : 0x00
bDeviceProtocol          : 0x00
bMaxPacketSize0          : 0x40 (64 bytes)
idVendor                 : 0x10C4 (Silicon Laboratories, Inc.)
idProduct                : 0x8468
bcdDevice                : 0x0000
iManufacturer            : 0x01 (String Descriptor 1)
 Language 0x0409         : "Tiqiaa"
iProduct                 : 0x02 (String Descriptor 2)
 Language 0x0409         : "Tview"
iSerialNumber            : 0x00 (No String Descriptor)
bNumConfigurations       : 0x01 (1 Configuration)
Data (HexDump)           : 12 01 10 01 00 00 00 40 C4 10 68 84 00 00 01 02   .......@..h.....
                           00 01                                             ..

```

Looking around a bit online, it appears that someone has done a fair amount of the heavy lifting, by reverse-engineering the device and protocol between ZaZa and this device:

https://habr.com/ru/post/494800/ (in russian. google translate link here: https://habr-com.translate.goog/ru/post/494800/?_x_tr_sl=auto&_x_tr_tl=en&_x_tr_hl=en&_x_tr_pto=wapp)

Based on that reversing there is and Interface class, driver and simple Windows application:
https://gitlab.com/XenRE/tiqiaa-usb-ir

another person also created python code based on that driver:
https://gitlab.com/normanr/tiqiaa-usb-ir-py

I'm hoping this is enough information to be able to made these inexpensive devices work with IrPlus!

If it helps, I'd be happy to send one of the dongles in the mail to help out the effort.

thanks!

**Comment by lukatavcer** [comment] 2023-02-20 18:47
> Hi All, After building a couple of ir blasters out of LEDs and 3.5mm jacks for my LG G7 - which worked, but do not have very good range...
> 
> In a spirit of experimentation I purchased a couple of these USB-C devices from amazon: https://www.amazon.com/dp/B083SNBP5W and https://www.amazon.com/dp/B07DFZ56MD
> 
> Here's some information that I dug up that I hope will be useful!
> 
> Plugging these into windows they both enumerate identically:
> 
> ```
>     ---------------------- Device Descriptor ----------------------
> bLength                  : 0x12 (18 bytes)
> bDescriptorType          : 0x01 (Device Descriptor)
> bcdUSB                   : 0x110 (USB Version 1.10)
> bDeviceClass             : 0x00 (defined by the interface descriptors)
> bDeviceSubClass          : 0x00
> bDeviceProtocol          : 0x00
> bMaxPacketSize0          : 0x40 (64 bytes)
> idVendor                 : 0x10C4 (Silicon Laboratories, Inc.)
> idProduct                : 0x8468
> bcdDevice                : 0x0000
> iManufacturer            : 0x01 (String Descriptor 1)
>  Language 0x0409         : "Tiqiaa"
> iProduct                 : 0x02 (String Descriptor 2)
>  Language 0x0409         : "Tview"
> iSerialNumber            : 0x00 (No String Descriptor)
> bNumConfigurations       : 0x01 (1 Configuration)
> Data (HexDump)           : 12 01 10 01 00 00 00 40 C4 10 68 84 00 00 01 02   .......@..h.....
>                            00 01                                             ..
> ```
> 
> Looking around a bit online, it appears that someone has done a fair amount of the heavy lifting, by reverse-engineering the device and protocol between ZaZa and this device:
> 
> https://habr.com/ru/post/494800/ (in russian. google translate link here: https://habr-com.translate.goog/ru/post/494800/?_x_tr_sl=auto&_x_tr_tl=en&_x_tr_hl=en&_x_tr_pto=wapp)
> 
> Based on that reversing there is an Interface class, driver and simple Windows application: https://gitlab.com/XenRE/tiqiaa-usb-ir
> 
> another person also created python code based on that driver: https://gitlab.com/normanr/tiqiaa-usb-ir-py
> 
> I'm hoping this is enough information to be able to made these inexpensive devices work with IrPlus!
> 
> If it helps, I'd be happy to send one of the dongles in the mail to help out the effort.
> 
> thanks!

Did you make it work?

**Comment by swinokur** [comment] 2023-02-21 02:51
> Did you make it work?

Hey there,
I was able to get it to work on a Windows VM - updating the driver is slightly tricky in that there are two USB devices that need their driver updated before the transceiver will start:
![image](https://user-images.githubusercontent.com/5185651/220231608-db0c386e-a0e6-4f32-85b0-92e41cabd7f8.png)

Here's device manager after installing the "TiqiaaUsbIr" (inf only) "driver":
![image](https://user-images.githubusercontent.com/5185651/220231835-931ef9c3-97b1-4879-aa26-78b99702635c.png)
You'll note the yellow "!".

Once the USB Input device is also updated:
![image](https://user-images.githubusercontent.com/5185651/220231937-0be2ca0f-c341-4468-bb85-ed8f54527a83.png)

at this point the CaptureIR program will start (and not give the annoying "no ir device found" message...)
![image](https://user-images.githubusercontent.com/5185651/220232033-e337fc06-c889-4af2-9258-c6fa71ec852c.png)

![image](https://user-images.githubusercontent.com/5185651/220232071-154c476c-89c9-4a11-b5a8-9b6961da3df9.png)

Pressing the "play" button will send that code to the transmitter, which has a visible red led "confidence" light that blinks on at the same time as the IR emitter blinks. (Verified with a phone camera)

I did not have the same luck with Linux. I tried xubuntu 22.10 (I figured I'd grab whatever was latest).

The Python code detects the device, and then sits there - seems like it is reading from stdin for code information. I tried using random typing on the keyboard, which is probably the wrong way.  I tried saving the sample IR from the windows IRCapture program and copying that over to Linux, the python code didn't like the sample file.

Perhaps someone could have a look at the python code and help me divine what it is looking for in an IR sample file?

Also in my digging, looks like someone did a libusb port of a "user space driver" to linux: 
https://gitlab.com/XenRE/tiqiaa-usb-ir/-/merge_requests/2/diffs?commit_id=b0731b48020b10114466a511fbcf3a862349af28
https://gitlab.com/XenRE/tiqiaa-usb-ir/-/tree/b0731b48020b10114466a511fbcf3a862349af28/Src

**Comment by HeadCrash66** [comment] 2023-04-15 07:33
Hi,

I found this USB-C devices too and would prefere an open source implemetation too instead of the shady ZaZa app.
After looking to the reverse engering linked above I would guess that this should be sufficent but also make much work.

But in comparsion to a dedicated Wifi/Blutooth I would prefere these USB dongles. Sure you have to carry them, but they are more handy and also do not require additional power or software care.

Just my 2ct, best regards.

**Comment by cantarini** [comment] 2023-05-20 13:57
Hello, same for me. I would lime to be able to use the usb c ir adapter from my samsung galaxy s22 with your app rather than from ZaZa app. 
Count me in for any help I could give

**Comment by wasiliysoft** [comment] 2023-09-02 17:51
I'm not sure if it [https://github.com/wasiliysoft/tiqiaa-usb-demo](https://github.com/wasiliysoft/tiqiaa-usb-demo) works correctly, I would be grateful if someone tests and writes about it. Collected bit by bit plus an article [https://habr.com/ru/post/494800/](https://habr.com/ru/post/494800/)

**Comment by irplus-remote** [comment] 2023-09-06 11:17
Hey, i'll check this out for sure and let you know =) i have a USB adapter to test with, and if it works i'd be happy to add support to irplus

**Comment by swinokur** [comment] 2023-09-15 03:20
This is exciting to read! @irplus-remote please let us know when there's a beta version to try out?!

**Comment by wasiliysoft** [comment] 2023-09-15 03:30
Well, I cheated a little when I wrote that I’m not sure if it works, because I’ve actually been using this code for a long time in my “ircode finder” application, but I really don’t have enough knowledge to make a standalone library or SDK out of it  , so I decided to publish the code in the hope that someone will take on it)

**Comment by masbaehr** [comment] 2023-09-15 06:38
Ive updated irplusLAN to include support for the dongle - just attach the dongle and you will be prompted to use it. Let me know if it worked for any one who wants to test it. 


Ill also try to make a lib out of it but it will probably be in Java i cant progam in Kotlin Yet :-) Thanks again.

**Comment by irplus-remote** [comment] 2023-09-15 06:40
Ive updated irplus lan to use the dongle. Just connect it and let me know if it worked..

Ill also try to make a Lib out of it as you requested but it will be probably in Java as i cant program in Kotlin Yet :)

**Comment by TomBPotochek** [comment] 2023-09-15 21:33
@irplus-remote seems to be working! I could control a TV with one of these USB ir dangles.

**Comment by flameshikari** [comment] 2023-09-15 23:31
Is there any marketplaces where I can buy that dongle or similar which will work with irplus? I can't find anything. AliExpress preferable!

**Comment by swinokur** [comment] 2023-09-15 23:39
> Is there any marketplaces where I can buy that dongle or similar which will work with irplus? I can't find anything. AliExpress preferable!

perhaps try this one: https://www.aliexpress.us/item/3256805796552455.html ? It sure looks identical to one of the products from Amazon. 

We're all just doing some testing here, so if you get this one and it does work - let everyone know!

**Comment by flameshikari** [comment] 2023-09-16 00:17
> > Is there any marketplaces where I can buy that dongle or similar which will work with irplus? I can't find anything. AliExpress preferable!
> 
> perhaps try this one: https://www.aliexpress.us/item/3256805796552455.html (click on the usb-c version)? It sure looks identical to one of the products from Amazon.
> 
> We're all just doing some testing here, so if you get this one and it does work - let everyone know!

Bought [this one](https://aliexpress.ru/item/1005005417256299.html). I'm not sure that link will load, so here's a picture of the dongle. Will arrive in a week. I'll keep you informed!

![2023-09-16_05-14-48_335](https://github.com/irplus-remote/irplus-codes.github.io/assets/17804422/73278351-a1b7-4a4e-897c-0a00287e93e7)

**Comment by swinokur** [comment] 2023-09-18 00:25
@irplus-remote - I just had a chance to try the beta of irplus-lan (v1.1 build 321) with the usb-c dongle. 
I used this one to test: https://www.amazon.com/dp/B07F7GPNF3
I tested with my Panasonic Plasma TV.
It works right away, which is fantastic! woo hoo! This is so exciting!

A couple things I've noticed:
- the USB-C device needs to be attached *before* launching the app.
- if I plug the device in *after* starting the app, the device will not work (no "confidence LED" lights on the device)
- if I unplug/replug the device while the app is running, the device will not work (no "confidence LED" lights on the device)
- to regain function, I have to unplug the device, and "swipe away" the app, before replugging and re-launching the app.

I'm on Android 9, LG G7.

If there's a trace I can send you please let me know what you might need.

**Comment by lmamakos** [comment] 2023-09-18 01:05
I'm so glad to see progress on this!   I just tried irplus-LAN with the USB dongle.   I was able to get it to emit *one* IR code, and then it doesn't function any longer.  If I kill the app and re-plug the USB dongle, it works again for one code.  I've not narrowed down the failure case any more than that.

I'm using a Pixel 7, on Android version 13.  If there's more specific information that I can provide, please let me know.  Thank you for working on this!

**Comment by wasiliysoft** [comment] 2023-09-18 02:05
> I'm so glad to see progress on this! I just tried irplus-LAN with the USB dongle. I was able to get it to emit _one_ IR code, and then it doesn't function any longer. If I kill the app and re-plug the USB dongle, it works again for one code. I've not narrowed down the failure case any more than that.
> 
> I'm using a Pixel 7, on Android version 13. If there's more specific information that I can provide, please let me know. Thank you for working on this!

Can you write information about the IR code you are sending?

**Comment by lmamakos** [comment] 2023-09-18 02:53
> Can you write information about the IR code you are sending?

I happened to be using the "VIZIO - TV-Generic" power-toggle code.   It did manage to work and power-on the TV.

However, I don't think it has anything to do with the specific code.  I was playing around a bit with other devices, and watching the IR emitter with a webcam -- that's what showed me that subsequent codes were not being transmitted.  If I exit the application (and kill it), I can see it transmit one code in the webcam preview, but no subsequent button presses.

**Comment by irplus-remote** [comment] 2023-09-18 15:36
I can confirm the problem - it seems to happen only with certain codefiles like the said VIZIO. I am investigating..

**Comment by irplus-remote** [comment] 2023-09-18 16:35
Maybe i've fixed it now with build 322 (irplusLAN) should available soon. It will also fix some issue with the widgets

**Comment by wasiliysoft** [comment] 2023-09-18 17:51
> Maybe i've fixed it now with build 322

Should I fix my example?

**Comment by irplus-remote** [comment] 2023-09-18 17:53
> > Maybe i've fixed it now with build 322
> 
> Should I fix my example?

yeah try to increase the timeout from 100ms to 250ms :)

**Comment by wasiliysoft** [comment] 2023-09-18 18:11
[byteWrite ](https://github.com/wasiliysoft/tiqiaa-usb-demo-android/blob/62178a25881e4f26152140aac2986834cfc36594/app/src/main/java/ru/wasiliysoft/tiqiaa_usb_demo/UsbIrService.kt#L134) and [bytesRead ](https://github.com/wasiliysoft/tiqiaa-usb-demo-android/blob/62178a25881e4f26152140aac2986834cfc36594/app/src/main/java/ru/wasiliysoft/tiqiaa_usb_demo/UsbIrService.kt#L136) ?

**Comment by lmamakos** [comment] 2023-09-18 18:24
> Maybe i've fixed it now with build 322 (irplusLAN) should available soon. It will also fix some issue with the widgets

I just tried the new version from the Google Play store, and it's now working!   This is wonderful; I can now once again fix the TV in hotel rooms that have been switched into some random mode/language/etc.  And now control the random things at home once again.

**Comment by wasiliysoft** [comment] 2023-09-18 18:29
> yeah try to increase the timeout from 100ms to 250ms :)

It's strange, but my code from the example sends the codes for "VISIO - TV-Generic" well, without changing the delay from 100 to 250. Is this exactly the only fix that has subordinated the work of the IrPlus LAN?

**Comment by irplus-remote** [comment] 2023-09-19 08:19
> > yeah try to increase the timeout from 100ms to 250ms :)
> 
> [byteWrite ](https://github.com/wasiliysoft/tiqiaa-usb-demo-android/blob/62178a25881e4f26152140aac2986834cfc36594/app/src/main/java/ru/wasiliysoft/tiqiaa_usb_demo/UsbIrService.kt#L134) and [bytesRead ](https://github.com/wasiliysoft/tiqiaa-usb-demo-android/blob/62178a25881e4f26152140aac2986834cfc36594/app/src/main/java/ru/wasiliysoft/tiqiaa_usb_demo/UsbIrService.kt#L136) ?
> 
> upd: It's strange, but my code from the example sends the codes for "VISIO - TV-Generic" well, without changing the delay from 100 to 250. Is this exactly the only fix that has subordinated the work of the IrPlus LAN?
> 
> upd2: Can this be noticeable only on Android 13?

I was able to reproduce it, with 100ms on the Vizio code it would work sometimes, and after a while if you press too fast maybe it stopped working. But with 250ms it did not happen again. Maybe there is also some "byte-sequence" you have to send to terminate a code? I don't know , i found it out just by trying out ;)

**Comment by irplus-remote** [comment] 2023-09-20 07:44
Im closing this issue for now as it _does work_ technically. So if there arise new problems it or other blasters should be supported - it would be better to open a new issue, so we dont have to read so many messages ;)

**Closed by irplus-remote** 2023-09-20 07:44 UTC
Labels: enhancement
